example:
  property: I AM DEFAULT

spring:
  cloud:
      stream:
        bindings:
          input:
            group: licensingGroup
            destination: orgChangeTopic
            content-type: application/json
        kafka:
          binder:
            zkNodes: kafka
            brokers: kafka
  database:
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    ddl-auto: none
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enable-by-default: true

keycloak:
  realm: spmia-realm
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: ostock
  credentials:
    secret: 92d6454f-f28f-489a-9235-ddad8c1cc7ee
  use-resource-role-mappings: true
  bearer-only: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/
