spring:
  cloud:
    stream:
      bindings:
        output:
          destination: orgChangeTopic
          content-type: application/json
      kafka:
        binder:
          zkNodes: kafka
          brokers: kafka
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    test-while-idle: true
    validation-query: SELECT 1

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
keycloak:
  realm: spmia-realm
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: ostock
  credentials:
    secret: 92d6454f-f28f-489a-9235-ddad8c1cc7ee
  use-resource-role-mappings: true
  bearer-only: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/




